# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: postgresql
  host: localhost
  database: christian_aid_development
  username: postgres
  password: 
    
#
test:
  adapter: postgresql
  host: localhost
  database: christian_aid_test
  username: postgres
  password:


production:
  adapter: mysql
  host: localhost
  database: camtgs
  username: camtgs
  password: PVuGVLRhmP
